### ISSUE TITLE
no linux builds

### ISSUE THREAD

**Issue by foxlldev** [quickdaffy/quickmind#367]
chads cannot use this app since there are no linux builds of it
chads use linux
build for linux

foxlmind, however, has linux builds now. get fucked.
https://github.com/foxlldev/foxlmind/releases

**Comment by quickdaffy** [comment]
hello,
please stop promoting skids of my code.
thanks,
quick

**Comment by foxlldev** [comment]
read your own readme

**Comment by quickdaffy** [comment]
i cant read

**Comment by JustNathan10** [comment]
foxldev is SKIDDDDDDDDDDDDDDDDDDD

**Comment by JustNathan10** [comment]
GAY SKIDDDDDDDD

**Comment by quickdaffy** [comment]
THATS ME (minus the skid part, foxldev is the real skid)

**Comment by quickdaffy** [comment]
no response? imagine 🥱
